# Generated by Django 5.1.6 on 2025-02-20 22:01

# Esta clase realiza la migración de las tabla de Tusuario
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.BooleanField(default='0')),
            ],
        ),
    ]
