# Generated by Django 5.1.6 on 2025-02-20 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=100)),
                ('fk_iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tusuario')),
            ],
        ),
    ]
