# Generated by Django 5.1.6 on 2025-02-20 22:28
# Esta clase realiza la migración de las tabla de TUsuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusuario',
            name='celular',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tusuario',
            name='ciudad',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tusuario',
            name='correo',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tusuario',
            name='direccion',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tusuario',
            name='documento',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tusuario',
            name='nombre',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tusuario',
            name='primer_apellido',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tusuario',
            name='segundo_apellido',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
