# Generated by Django 5.1.6 on 2025-02-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tusuario_celular_tusuario_ciudad_tusuario_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tlogin',
            old_name='contrasena',
            new_name='contrasenaLogin',
        ),
        migrations.AlterField(
            model_name='tusuario',
            name='rol',
            field=models.BooleanField(),
        ),
    ]
